# Generated by Django 6.0.4 on 2026-05-06 08:33

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('id_type', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitors/photos/')),
                ('fingerprint_data', models.TextField(blank=True, null=True)),
                ('id_proof_document', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator / Front Desk'), ('SECURITY', 'Security Guard')], default='SECURITY', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('host', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('status', models.CharField(default='REGISTERED', max_length=20)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('entry_time', models.TimeField(default=api.models.get_current_time)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('rfid_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('blacklist_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_logs', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.visitor')),
            ],
        ),
    ]
