# Generated by Django 6.0.4 on 2026-05-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='valid_until',
        ),
    ]
