# Generated by Django 6.0.4 on 2026-05-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_visitor_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
