# Generated by Django 6.0.4 on 2026-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_visitor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='expected_exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='expected_exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
