# Generated by Django 6.0.5 on 2026-05-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_visitorlog_expected_exit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator / Front Desk'), ('SECURITY', 'Security Guard'), ('USER', 'Normal User')], default='SECURITY', max_length=20),
        ),
    ]
