# Generated by Django 6.0.5 on 2026-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='police_verification_document',
            field=models.FileField(blank=True, null=True, upload_to='police_certs/'),
        ),
    ]
