# Generated by Django 6.0.5 on 2026-05-14 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_visitorlog_police_verification_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fingerprint_data', models.TextField()),
                ('id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('id_proof_document', models.FileField(blank=True, null=True, upload_to='group_id_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='api.visitorlog')),
            ],
        ),
    ]
