# Generated by Django 6.0.5 on 2026-05-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_groupvisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='escort',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
