# Generated by Django 6.0.5 on 2026-05-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_visitor_escort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='escort',
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='escort',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
