# Generated by Django 6.0.5 on 2026-05-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_visitor_escort_visitorlog_escort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupvisitor',
            name='fingerprint_data',
        ),
        migrations.AddField(
            model_name='groupvisitor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_visitors/photos/'),
        ),
    ]
