# Generated by Django 6.0.5 on 2026-05-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_groupvisitor_fingerprint_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(default='NORMAL', max_length=20),
        ),
    ]
