# Generated by Django 6.0.5 on 2026-05-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_visitor_visitor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='visit_id',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
