# Generated by Django 6.0.5 on 2026-05-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_visitorlog_visit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='escort_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='escort_rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
