# Generated by Django 6.0.5 on 2026-05-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_visitorlog_escort_phone_visitorlog_escort_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitorlog',
            old_name='escort_rank',
            new_name='mobile_locker',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='escort_phone',
        ),
    ]
