# Generated by Django 6.0.5 on 2026-06-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_escort_rank_visitorlog_mobile_locker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='escort_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='escort_rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
